### ISSUE TITLE
How to use this Plugin directly in a C++ Class?

### ISSUE THREAD

**Issue by jemishGhoghari** [videofeedback/Unreal_Engine_SerialCOM_Plugin#14]
Hello @videofeedback 

I have a question about this Plugin. Is it possible to use this Plugin directly in a C++ class? If so, Can you give me some hints? I want this Plugin to read data from Arduino Due over Serial Port.
 
I appreciate any help you can provide.

Regards
Jemish

**Comment by videofeedback** [comment]
You can. Look at the C++ calls from this folder: 
https://github.com/videofeedback/Unreal_Engine_SerialCOM_Plugin/tree/main/SerialCOM/Source/SERIALCOM
